### ISSUE TITLE
unclear what i missed

### ISSUE THREAD

**Issue by g-pechorin** [timofurrer/pandoc-mermaid-filter#5]
I am unfamiliar with mermaid/pandoc.

For those like me;
- how do I know if mermaid is on my path? `mmdc` works
  - ... you meant this right? https://github.com/mermaidjs/mermaid.cli
- this works on windows ... right?

**Comment by ghost** [comment]
Not sure if still relevant, but I can answer your questions:

 - You need to [create the environment variable](https://github.com/knsv/mermaid/issues/790) `MERMAID_BIN` and set it to where `npm` or `yarn` installed the mmdc binary. In my case I set the environment variable to `c:\Users\username\node_modules\.bin\mmdc.cmd`. Note that I pointed it to the `mmdc.cmd`, not to the plain `mmdc` file which is in that same folder.
 - Yes, this works on Windows if you follow above step. If not, post back with an error message.

**Comment by timofurrer** [comment]
I hope @ba-tno answered your question :)
